(library (scheme time)
  (export current-second current-jiffy jiffies-per-second)
  (import (chezscheme))
  (define (current-second)
    (inexact (time-second (current-time))))
  (define (current-jiffy)
    (let ((now (current-time)))
      (+ (* (time-second now) 1000000000)
         (time-nanosecond now))))
  (define (jiffies-per-second) 1000000000))
